swagger: '2.0'
info:
  description: Get Windfarm info and status
  version: 1.0.0
  title: Windfarm API
  contact:
    email: lalevee@google.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html


schemes:
 - https
 
host: 34.117.38.184.nip.io
basePath: /windfarms/v1
 
# tags are used for organizing operations
tags:
- name: Windfarm 
  description: Operations available to regular developers

produces:
- application/json
security:
- api_key: []

paths:
  /farms:
    get:
      tags:
      - Windfarm
      summary: filtered list of windfarms
      operationId: listWindfarms
      description: |
        By passing in the appropriate filtering options, you can list existing windfarms
      produces:
      - application/json
      parameters:
      - in: query
        name: limit
        description: number of max windfarm elements to be return
        required: true
        type: integer
        default: 2
      - in: query
        name: country
        description: ISO country code
        required: true
        type: string
        default: 'FR'
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/listWindfarms'
        400:
          description: bad input parameter
  /farms/{id}:
    get:
      tags:
      - Windfarm
      summary: get Windfarm data
      operationId: getWindfarm
      description: |
        By passing in the appropriate options, you can search for a wind farm detailled info
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: pass the windfarm id string for looking up info
        required: true
        type: integer
        default: 20
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/windfarms'
        400:
          description: bad input parameter
  /status/{id}:
    get:
      tags:
      - Windfarm
      summary: windfarm status for a given date
      operationId: getWindfarmsStatus
      description: |
        By passing in the appropriate filtering options, you can list existing windfarms
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: windfarm id
        required: true
        type: integer
        default: 20
      - in: query
        name: date
        description: Date
        required: true
        type: string
        default: '20/05/22'
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/windfarmsStatus'
        400:
          description: bad input parameter
definitions:
  listWindfarms:
    type: array
    items:
      $ref: '#/definitions/windfarms'
  windfarms:    
    type: object
    properties:
      ID:
        type: integer
        example: 20
      Continent: 
        type: string
        example: "Europe"
      ISOcode: 
        type: string
        example: "FR"
      Country: 
        type: string
        example: "France"
      State code: 
        type: string
        example: "#ND"
      Area: 
        type: string
        example: "11 (Occitanie)"
      City: 
        type: string
        example: "Roquetaillade"
      Name: 
        type: string
        example: "Roquetaillade"
      2nd name: 
        type: string
        example: "#ND"
      Latitude: 
        type: number
        example: 43.001
      Longitude: 
        type: number
        example: 2.233
      Altitude/Depth: 
        type: string
        example: "595/645"
      Location accuracy: 
        type: string
        example: "Yes"
      Offshore/Shore distance: 
        type: string
        example: "No"
      Manufacturer: 
        type: string
        example: "Gamesa"
      Turbine: 
        type: string
        example: "G47/660"
      Hub height: 
        type: integer
        example: 47
      Number of turbines: 
        type: integer
        example: 8
      Total power: 
        type: integer
        example: 5280
      Developer: 
        type: string
        example: "Compagnie du Vent"
      Operator: 
        type: string
        example: "Engie"
      Owner: 
        type: string
        example: "Engie"
      Commissioning date: 
        type: string
        example: "2001/10"
      Status: 
        type: string
        example: "Production"
  windfarmsStatus:
    type: object
    properties:
      NomFerme: 
        type: string
        example: "#ND"
      Pays: 
        type: string
        example: "France"
      Region: 
        type: string
        example: "11 (Occitanie)"
      Ville: 
        type: string
        example: "Roquetaillade"
      Puissance:
        type: integer
        example: 5280
      Conditions: 
        type: string
        example: "Clouds"
      Vent: 
        type: integer
        example: 0
      Temperature: 
        type: integer
        example: 12
      Statut: 
        type: string
        example: "EN MARCHE"

securityDefinitions:
  api_key:
    type: apiKey
    name: x-apikey
    in: header
    
