
name: Apigee API Hub CI with Maven

on: push

jobs:
  conditional_job_check_files:
    runs-on: 'ubuntu-20.04'
    # Declare outputs for next jobs
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2

    - name: check_file_changed_bash
      run: |
        # Diff HEAD with the previous commit
        diff=$(git diff --name-only HEAD^ HEAD)
        echo "found:" $diff


    - shell: pwsh
      id: check_file_changed
      if: ${{ env.docs_changed }}
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD
        echo "found:" $diff

        # Check if apiHub/api-config.yaml or apiHub/specs/¨.yaml or json updated
        specConfigDiff=$(echo $diff | tr " " "\n" | grep -E "apiHub/api-config.yaml|apiHub/specs/.+\.(json|yaml)")

        echo "found 2:" $specConfigDiff 

        specConfigHasDiff=$(echo $specConfigDiff | wc -w)
        echo "found 3:" $specConfigHasDiff "-"" $specHasDiff

        if (( -z $specDiff ))
        then
          updateHub=true
        else
          updateHub=false
        fi

        echo "found 4:" $updateHub

        # Set the output named "docs_changed"
        "updateHub=$updateHub" >> $env:GITHUB_ENV

    - name: conditional
      if: ${{ env.updateHub }}
      run: |
        echo "-> " $updateHub
      env:
        change: ${{ env.updateHub }}
