
name: Apigee API Hub CI with Maven

on: push

jobs:
  conditional_job_check_files:
    runs-on: 'ubuntu-20.04'
    # Declare outputs for next jobs
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2

    - name: check_file_changed_bash
      shell: bash {0}
      run: |
        # Diff HEAD with the previous commit
        diff=$(git diff --name-only HEAD^ HEAD)
        echo "found:" $diff

        # Check if spec config changed
        specConfigDiff=$(echo $diff | tr " " "\n" | grep -E "apiHub/api-config.yaml|apiHub/specs/.+\.(json|yaml)")

        echo "found 2:" $specConfigDiff 

        if (( -z $specConfigDiff ))
        then
          updateHub=true
        else
          updateHub=false
        fi

        echo "found 4:" $updateHub

        # Set the output named "docs_changed"
        echo "updateHub=$updateHub" >> $env:GITHUB_ENV

 

    - name: conditional
      if: ${{ env.updateHub }}
      run: |
        echo "-> " $updateHub
      env:
        change: ${{ env.updateHub }}
