
name: Apigee API Hub CI with Maven

on: push

env:

  # Default Target Apigee Organization et environment (can be also be dynamically defined in [Set Variables *] steps)
  APIGEE_ORG: bap-emea-apigee-5
  APIGEE_ENV: default-dev
  TEST_HOST: 34.117.38.184.nip.io
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

jobs:
  Apigee-Deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

jobs:
  Apigee-Api-Hub-Deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2

      # Generate SA key file from secret variable
      - name: Generate SA key file
        run: | 
          echo $GCP_SERVICE_ACCOUNT > sa.json

      # Check if ApiHub config file or specification file changed      
      - name: check_spec_file_changed
        shell: bash {0}
        run: |
          # Diff HEAD with the previous commit
          diff=$(git diff --name-only HEAD^ HEAD)
          echo "Files updated in last commit:" $diff

          # Check if spec file(s) changed
          specConfigDiff=$(echo $diff | tr " " "\n" | grep -E "apiHub/api-config.yaml|apiHub/specs/.+\.(json|yaml)")

          if [ -z "$specConfigDiff" ]
          then
            updateHub=false
          else
            updateHub=true
          fi

          # Set updateHub trigger
          echo "updateHub=$updateHub" >> $GITHUB_ENV

      # Create/Update API in API Hub  
      - name: update Apigee Api Hub
        if: ${{ env.updateHub }}
        run: |
          mvn install -Pdev -DprojectId=$APIGEE_ORG -Doptions=create -Dfile=sa.json
