
name: Apigee API Hub CI with Maven

on: push
    
jobs:
  Test-File:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2

      - name: Set Variables for [Main] branch
        run: |
          # Diff HEAD with the previous commit
          diff=$(git diff --name-only)

          echo "diff : " $diff 
