
name: Apigee API Hub CI with Maven

on: push

env:
  # Default Target Apigee Organization et environment (can be also be dynamically defined in [Set Variables *] steps)
  APIGEE_ORG: bap-emea-apigee-5
  APIGEE_ENV: default-dev
  TEST_HOST: 34.117.38.184.nip.io
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

jobs:
  Apigee-Commit-Check:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    # Map step outputs to a job outputs
    outputs:
      updateHub: ${{ steps.check_files_changed.outputs.updateHub }}
      updateProxy: ${{ steps.check_files_changed.outputs.updateProxy }}

    steps:
      - uses: actions/checkout@v3
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2

      # Check if ApiHub config file or specification file changed      
      - name: check_files_changed
        id: check_files_changed
        shell: bash {0}
        run: |
          # Diff HEAD with the previous commit
          diff=$(git diff --name-only HEAD^ HEAD)
          echo "Files updated in the last commit:" $diff

          # Check if spec file(s) changed
          specConfigDiff=$(echo $diff | tr " " "\n" | grep -E "apiHub/api-config.yaml|apiHub/specs/.+\.(json|yaml)")

          if [ -z "$specConfigDiff" ]
          then
            echo "No Api change"
          else
            echo "Api change"
            echo "updateHub=true" >> $GITHUB_ENV
            echo "updateHub=true" >> $GITHUB_OUTPUT
          fi
          
          # Check if Apigee Proxy file(s) changed
          apiProxyDiff=$(echo $diff | tr " " "\n" | grep -E "apiProxy/apiproxy/.*")
          if [ -z "$apiProxyDiff" ]
          then
            echo "No proxy change"
          else
            echo "Proxy change"
            echo "updateProxy=true" >> $GITHUB_ENV
            echo "updateProxy=true" >> $GITHUB_OUTPUT
          fi
          
          echo "specConfigDiff=" $specConfigDiff 
          echo "apiProxyDiff=" $apiProxyDiff

  

  Apigee-Proxy-Deploy:
    needs: Apigee-Commit-Check
    #if: ${{ needs.Apigee-Commit-Check.outputs.updateProxy }} 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: skip-if
        run: | 
          echo "exit if no proxy update"
          if [[ -z "${{ needs.Apigee-Commit-Check.outputs.updateProxy }}" ]]
          then 
            exit 1
          fi
          
      # Generate SA key file from secret variable
      - name: Generate SA key file
        run: | 
          echo $GCP_SERVICE_ACCOUNT > sa.json

      # Create/Update API in API Mgt  
      - name: update Apigee Proxy
        run: |
          echo "deploy proxy ? " echo ${{ needs.Apigee-Commit-Check.outputs.updateProxy }}



  Apigee-Hub-Deploy:
    needs: [Apigee-Proxy-Deploy]
    if: always()
    #if: ${{ needs.Apigee-Commit-Check.outputs.updateHub }} 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Generate SA key file from secret variable
      - name: Generate SA key file
        run: | 
          echo $GCP_SERVICE_ACCOUNT > sa.json

      # Create/Update API in API Hub  
      - name: update Apigee Api (Hub)
        run: |
          cd apiHub
          # mvn install -Pdev -DprojectId=$APIGEE_ORG -Doptions=create -Dfile=../sa.json --no-transfer-progress


