
name: Apigee API Hub CI with Maven

on: push

env:
  # Default Target Apigee Organization et environment (can be also be dynamically defined in [Set Variables *] steps)
  APIGEE_ORG: bap-emea-apigee-5
  APIGEE_ENV: default-dev
  TEST_HOST: 34.117.38.184.nip.io
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

jobs:
  Apigee-Commit-Check:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    # Map step outputs to a job outputs
    outputs:
      updateHub: ${{ steps.check_files_changed.outputs.updateHub }}
      updateProxy: ${{ steps.check_files_changed.outputs.updateProxy }}

    steps:
      - uses: actions/checkout@v3
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2

      # Check if ApiHub config file or specification file changed      
      - name: check_files_changed
        id: check_files_changed
        shell: bash {0}
        run: |
          # Diff HEAD with the previous commit
          diff=$(git diff --name-only HEAD^ HEAD)
          echo "Files updated in the last commit:" $diff

          # Check if spec file(s) changed
          specConfigDiff=$(echo $diff | tr " " "\n" | grep -E "apiHub/api-config.yaml|apiHub/specs/.+\.(json|yaml)")

          if [ -z "$specConfigDiff" ]
          then
            echo "No Api change"
          else
            echo "Api change -> [" $specConfigDiff "]"
            echo "updateHub=true" >> $GITHUB_ENV
            echo "updateHub=true" >> $GITHUB_OUTPUT
          fi
          
          # Check if Apigee Proxy file(s) changed
          apiProxyDiff=$(echo $diff | tr " " "\n" | grep -E "apiProxy/apiproxy/.*")
          if [ -z "$apiProxyDiff" ]
          then
            echo "No proxy change"
          else
            echo "Proxy change -> [" $apiProxyDiff "]"
            echo "updateProxy=true" >> $GITHUB_ENV
            echo "updateProxy=true" >> $GITHUB_OUTPUT
          fi
  




  Apigee-Proxy-Deploy:
    needs: Apigee-Commit-Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Determine if allsteps in this job must be skipped
      # Currently it is not possible to early-exit the job with "success" status
      # See: https://github.com/actions/runner/issues/662
      - name: run-step-if
        run: | 
          echo "exit if no proxy update"
          if [[ -n "${{ needs.Apigee-Commit-Check.outputs.updateProxy }}" ]]
          then 
            echo "run_step=true" >> $GITHUB_ENV
          else
            echo "Job not needed; no update in apiProxy folder."
            echo "Skip all following steps."
          fi

      # Generate SA key file from secret variable
      - name: Generate SA key file
        if: ${{ env.run_step }}
        run: | 
          echo $GCP_SERVICE_ACCOUNT > sa.json

      # Create/Update API in API Mgt  
      - name: update Apigee Proxy
        if: ${{ env.run_step }}
        run: |
          echo "deploy proxy ? " echo ${{ needs.Apigee-Commit-Check.outputs.updateProxy }}





  Apigee-Hub-Deploy:
    needs: [Apigee-Commit-Check, Apigee-Proxy-Deploy]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Determine if allsteps in this job must be skipped
      # Currently it is not possible to early-exit the job with "success" status
      # See: https://github.com/actions/runner/issues/662
      - name: run-step-if
        run: | 
          echo "exit if no proxy update"
          if [[ -n "${{ needs.Apigee-Commit-Check.outputs.updateHub }}" ]]
          then 
            echo "run_step=true" >> $GITHUB_ENV
          else
            echo "Job not needed; no update in apiHub folder."
            echo "Skip all following steps."
          fi

      # Generate SA key file from secret variable
      - name: Generate SA key file
        if: ${{ env.run_step }}
        run: | 
          echo $GCP_SERVICE_ACCOUNT > sa.json

      # Create/Update API in API Hub  
      - name: update Apigee Api (Hub)
        if: ${{ env.run_step }}
        run: |
          cd apiHub
          mvn install -Pdev -DprojectId=$APIGEE_ORG -Doptions=create -Dfile=../sa.json --no-transfer-progress


